### ISSUE TITLE
ios模块clone下来，在xcode里面怎么使用，在模拟器跑不起来

### ISSUE THREAD

**Issue by fangjj** [apicloudcom/photoBrowser#3]
ios模块clone下来，在xcode里面怎么使用，打开PhotoBrowser.xcodeproj在模拟器跑不起来，求助？

**Comment by sunzhengcuan** [comment]
本工程只是模块静态库编译工程。模块开发工程去APICloud官网下载。建议直接真机调试，最终都是要运行在真机上的。如果编译包含模拟器库最终编译的库会大很多。
